### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by alisterscott** [perryn/blinky#1]
It'd be great to see this support Windows.
Currently this gem is dependent on ruby-usb 0.2.1 which isn't windows compatible.
The latest windows compatible ruby-usb gem is 0.1.3 (see: http://rubygems.org/gems/ruby-usb)
Alternatively you could use the libusb gem which is much more active, and also fully Windows compatible: https://github.com/larskanis/libusb

Thanks

**Comment by perryn** [comment]
Ill try to get to it, but I have a big backlog of other stuff at the moment

**Comment by perryn** [comment]
I have released a new version that uses libusb and should provide windows support: 0.0.5
