### ISSUE TITLE
Port to Java

### ISSUE THREAD

**Issue by rastadrian** [perryn/blinky#13]
Hey @perryn I am currently working on porting this project to java, I am going to be basing myself a lot on the structure of this one so I just wanted to both give you a heads up and to confirm if you were ok with it.

I am also still not set on the name but one of my choices was `jblinky`, which also made me wonder if you had any issue with that as well.

Let me know any comments or concerns, thank you!

**Comment by perryn** [comment]
Hi @rastadrian 

No problems, do what you like!  

I'm curious to know why you want to though?

**Comment by rastadrian** [comment]
Hey @perryn 

Thanks man, I have some reasons:
1. I had an issue with the CCTray monitoring (I believe the culprit was Chicanery though) where the request time to our Jenkins CCTray would increase exponentially up until a point where every request takes around a minute and a half.
2. Our jenkins contains multiple directories for different categories of projects (every directory contains its own `cc.xml` tray) so I wanted the application to only download the tray once and verify the specified jobs on that tray, rather than re-downloading the tray per job check (I believe that check is handled by Chicanery as well?).
3. When our team manager saw the light (literally) he got excited and now he wanted to "verify" other things, not only Jenkins CCTrays but also Service Health Probes, Internal File Contents and even Time (like an alarm, at certain time, turn yellow for a moment) so I needed to heavily extend the library and I'm not very experienced with Ruby and here at work we have a big Java community.
4. Luckily LibUSB is also ported to java, so I could use an architecture very similar to `blinky`.
5. And now that the light verifies so many stuff, our team also wanted a UI that showed the reasons the lights went red, so by using Java I could  create a web application using Spring Framework which is heavily supported at work.

Thank you again for the inspiration!
Here's the `jBlinky` project: https://github.com/rastadrian/jblinky
