### ISSUE TITLE
Blinkt! only supported on Linux

### ISSUE THREAD

**Issue by duncan-bayne** [perryn/blinky#14]
I'm working on a PR to add Blinkt! support to blinky, but it turns out the blinkt Gem has dependencies that are Linux-only (and _very_ Linux-only, relying on kernel functionality not present in other OSs).

Assuming non-Linux OSs are important targets for blinky (e.g. mention of Windows in the docs), I wonder how to proceed here.

There's an [open issue on bundler](https://github.com/bundler/bundler-features/issues/4) about supporting OS-specific groups, but no progress as of yet.

I guess I could always maintain a Blinkt!-specific fork, but that feels a bit hacky.

Thoughts?

**Comment by perryn** [comment]
I think we discussed this in person and it turned out Blinkt! was not a USB light, so it isn't really playing in the same sandpit as blinky anyway?
