### ISSUE TITLE
compatibility with chicanery 0.0.8

### ISSUE THREAD

**Issue by caifara** [perryn/blinky#2]
the run_every method has been removed (or changing gemspec to only allow 0.0.7)

**Comment by markryall** [comment]
Hmm - yes - it seemed to remove some duplication but makes it slightly more difficult to skip the execute method.

Probably easiest to now just: loop { run; sleep 15 }

**Comment by markryall** [comment]
Actually - forget about that - i've reintroduced run_every in version 0.1.0.  It'll nicely handle interrupt exceptions for you.

Sorry about that.  Seems pretty rude to break compatibility with the only one project you know has yours as a dependency :)

**Comment by caifara** [comment]
Great that this moves fast. Blinky's gemspec will need an updated dependency on chicanery as it's version moved beyond the 0.0 series.

**Comment by perryn** [comment]
I have released a new version of blinky with updated gemspec. I don't have any lights with me right now to check it works - please let me know

**Comment by perryn** [comment]
I recently sucessfully ran a light with the latest version so closing on the assumption all is good
