### ISSUE TITLE
Unable to install on OS X 10.8.3

### ISSUE THREAD

**Issue by sgvj** [perryn/blinky#4]
Very excited to use this!
I have the latest command-line tools and brew is updated. Libusb installs no problem.
When I 'sudo gem install blinky' on 10.8.3 it fails, please help.
Install ends with:
"Configuring libffi for i386
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: error: in `/Library/Ruby/Gems/1.8/gems/ffi-1.8.1/ext/ffi_c/libffi-i386':
configure: error: C compiler cannot create executables"
See`config.log' for more details
make[1]: **\* No targets specified and no makefile found.  Stop.

**Comment by perryn** [comment]
Hi there 

Looks like you are having trouble installing the ffi gem ( blinky depends on libusb which in turn depends on ffi)

It is pretty hard to see what the problem might be from that error message. If you take a look it suggests that you might find better details in the "console.log" file.

Take a look in there and see if it is of more help, or perhaps the authors of ffi might be able to help more: https://github.com/ffi/ffi

Just a hunch - have you installed the Apple Developer Tools? If you haven't you probably don't have a c compiler..

**Comment by perryn** [comment]
closing this given no update for a while
